version: 2

build:
  apt_packages:
    - graphviz
  os: ubuntu-24.04
  tools:
    python: '3.10'

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all

formats: []
