name: Install IBM ILOG CPLEX Optimization Studio

inputs:
  CPLEX_STUDIO_DOWNLOAD_URL:
    description: Dowload URL for IBM ILOG CPLEX Optimization Studio
    required: true

runs:
  using: composite
  steps:
    - name: Install "expect" tool
      shell: bash
      run: sudo apt-get -y install expect
    - name: Download installer
      shell: bash
      run: curl -Lo cplex.bin "$CPLEX_STUDIO_DOWNLOAD_URL" && chmod +x cplex.bin
      env:
        CPLEX_STUDIO_DOWNLOAD_URL: ${{ inputs.CPLEX_STUDIO_DOWNLOAD_URL }}
    - name: Run installer
      shell: bash
      run: expect -c "spawn ./cplex.bin" -f "$GITHUB_ACTION_PATH/cplex.expect"
    - name: Remove download
      shell: bash
      run: rm cplex.bin
