# -*- coding: utf-8 -*-
# Licensed under a 3-clause BSD style license - see LICENSE.rst
#
# Astropy documentation build configuration file.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this file.
#
# All configuration values have a default. Some values are defined in
# the global Astropy configuration which is loaded here before anything else.
# See astropy.sphinx.conf for which values are set there.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
# sys.path.insert(0, os.path.abspath('..'))
# IMPORTANT: the above commented section was generated by sphinx-quickstart, but
# is *NOT* appropriate for astropy or Astropy affiliated packages. It is left
# commented out with this explanation to make it clear why this should not be
# done. If the sys.path entry above is added, when the astropy.sphinx.conf
# import occurs, it will import the *source* version of astropy instead of the
# version installed (if invoked as "make html" or directly with sphinx), or the
# version in the build directory (if "python setup.py build_sphinx" is used).
# Thus, any C-extensions that are needed to build the documentation will *not*
# be accessible, and the documentation will not build correctly.

import datetime
import os
import sys
from importlib import import_module

import tomllib

try:
    from sphinx_astropy.conf.v2 import *  # noqa
except ImportError:
    print(
        "ERROR: the documentation requires the sphinx-astropy package to be installed"
    )
    sys.exit(1)

# Get configuration information from pyproject.toml

with open(os.path.join(os.path.dirname(__file__), "..", "pyproject.toml"), "rb") as f:
    project_metadata = tomllib.load(f)["project"]

# -- General configuration ----------------------------------------------------

# By default, highlight as Python 3.
highlight_language = "python3"

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.2'

# To perform a Sphinx version check that needs to be more specific than
# major.minor, call `check_sphinx_version("X.Y.Z")` here.
# check_sphinx_version("1.2.1")

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns.append("_templates")  # noqa: F405

# This is added to the end of RST files - a good place to put substitutions to
# be used globally.
rst_epilog += r"""
.. |M4OPT| replace:: M\ :sup:`4`\ OPT
"""  # noqa: F405

# -- Project information ------------------------------------------------------

# This does not *have* to match the package name, but typically does
project = project_metadata["name"]
author = project_metadata["authors"][0]["name"]
copyright = "{0}, {1}".format(datetime.datetime.now().year, author)

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.

import_module(project_metadata["name"])
package = sys.modules[project_metadata["name"]]

# The short X.Y version.
version = package.__version__.split("-", 1)[0]
# The full version, including alpha/beta/rc tags.
release = package.__version__

# Only include dev docs in dev version.
dev = "dev" in release


# -- Options for HTML output --------------------------------------------------

# A NOTE ON HTML THEMES
# The global astropy configuration uses a custom theme, 'bootstrap-astropy',
# which is installed along with astropy. A different theme can be used or
# the options for this theme can be modified by overriding some of the
# variables set in the global configuration. The variables set in the
# global configuration are listed below, commented out.


# Add any paths that contain custom themes here, relative to this directory.
# To use a different custom theme, add the directory containing the theme.
# html_theme_path = []

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes. To override the custom theme, set this to the
# name of a builtin theme or the name of a custom theme in html_theme_path.
# html_theme = None

html_static_path = ["_static"]
html_css_files = [
    "css/risk_table.css",
]


# Custom sidebar templates, maps document names to template names.
# html_sidebars = {}

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
# html_logo = ''

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
# html_favicon = ''

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
# html_last_updated_fmt = ''

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = "M⁴OPT"

# Output file base name for HTML help builder.
htmlhelp_basename = project + "doc"

# Prefixes that are ignored for sorting the Python module index
modindex_common_prefix = ["m4opt."]

html_theme_options.update(  # noqa: F405
    {
        "github_url": "https://github.com/m4opt/m4opt",
        "use_edit_page_button": True,
    }
)

html_context = {
    "default_mode": "light",
    "to_be_indexed": ["stable", "latest"],
    "is_development": dev,
    "github_user": "m4opt",
    "github_repo": "m4opt",
    "github_version": "main",
    "doc_path": "docs",
}

# -- Options for LaTeX output -------------------------------------------------

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
    ("index", project + ".tex", project + " Documentation", author, "manual")
]


# -- Options for manual page output -------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [("index", project.lower(), project + " Documentation", [author], 1)]


# -- Options for the edit_on_github extension ---------------------------------

extensions += ["sphinx_astropy.ext.edit_on_github"]  # noqa: F405

edit_on_github_project = "m4opt/m4opt"
edit_on_github_branch = "main"

edit_on_github_source_root = ""
edit_on_github_doc_root = "docs"

# -- Resolving issue number to links in changelog -----------------------------
github_issues_url = "https://github.com/{0}/issues/".format(edit_on_github_project)


# -- Options for linkcheck output -------------------------------------------
linkcheck_retry = 5
linkcheck_ignore = [
    r"https://github\.com/m4opt/m4opt/(?:issues|pull)/\d+",
]
linkcheck_timeout = 180
linkcheck_anchors = False

# -- Turn on nitpicky mode for sphinx (to warn about references not found) ----
#
# nitpicky = True
# nitpick_ignore = []
#
# Some warnings are impossible to suppress, and you can list specific references
# that should be ignored in a nitpick-exceptions file which should be inside
# the docs/ directory. The format of the file should be:
#
# <type> <class>
#
# for example:
#
# py:class astropy.io.votable.tree.Element
# py:class astropy.io.votable.tree.SimpleElement
# py:class astropy.io.votable.tree.SimpleElementWithContent
#
# Uncomment the following lines to enable the exceptions:
#
# for line in open('nitpick-exceptions'):
#     if line.strip() == "" or line.startswith("#"):
#         continue
#     dtype, target = line.split(None, 1)
#     target = target.strip()
#     nitpick_ignore.append((dtype, six.u(target)))


# -- Options for intersphinx --------------------------------------------------
intersphinx_mapping.update(  # noqa: F405
    {
        "astropy": ("https://docs.astropy.org/en/stable/", None),
        "astropy_healpix": ("https://astropy-healpix.readthedocs.io/en/stable/", None),
        "docplex": ("http://ibmdecisionoptimization.github.io/docplex-doc/mp/", None),
        "dust-extinction": ("https://dust-extinction.readthedocs.io/en/latest/", None),
        "ligo.skymap": ("https://lscsoft.docs.ligo.org/ligo.skymap/", None),
        "pip": ("https://pip.pypa.io/en/stable/", None),
        "regions": ("https://astropy-regions.readthedocs.io/en/stable/", None),
        "synphot": ("https://synphot.readthedocs.io/en/stable/", None),
        "userguide": ("https://emfollow.docs.ligo.org/userguide/", None),
    }
)

# -- Options for plot_directive -----------------------------------------------
plot_include_source = True
plot_formats = [("svg", 300), ("pdf", 300)]
plot_html_show_formats = False


# -- Options for the sphinx.ext.todo extension --------------------------------
# extensions += ['sphinx.ext.todo']
todo_include_todos = True


# -- Options for the sphinxcontrib.typer extension ----------------------------
extensions += ["sphinxcontrib.typer"]


# -- Merge type annotations with numpydoc parameter docstrings ----------------
extensions.remove("numpydoc")
extensions.append("sphinx.ext.napoleon")
autodoc_typehints = "description"


# -- Options for the sphinxcontrib.bibtex extension ---------------------------
extensions += ["sphinxcontrib.bibtex"]
bibtex_bibfiles = ["refs.bib"]
