name: Publish

permissions: {}

on:
  schedule:
    # run every day at 4am UTC
    - cron: '0 4 * * *'
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  publish:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@4193751d511425d4edc1d5657c24b2128d49b017  # v2.6.4
    secrets:
      pypi_token: ${{ secrets.pypi_token }}
